### ISSUE TITLE
Bug in Firebase ESP32 Client

### ISSUE THREAD

**Issue by pei-dev** [mobizt/mobizt#1]
Hi,

I turn to you because I could not find too much information on forums and in the end the only one who is able to solve the problem is the author of the library. I have a nodemcu ESP32-S, which I connect to RealTime Database to send and read data. Everything works correctly, but it always 'breaks' when it reaches 100 read or write requests. Each one follows its own independent counter, and of course, when it restarts, it takes about 10s to re-establish the connection and send data again. I used the example of the library and it does exactly the same, so it must be a bug in the library that I hope I can fix as soon as possible, because it is urgent. 

Thank you very much for your help.

**Comment by mobizt** [comment]
You should post an issue in the library repository instead and should provide the clean (no third party libs), clear (basic code) and minimal sketch to reproduce the error.

You should debug your code for free memory, internet accessibility status at any portion of your code. 

The board power supply weakness (unstable), too long and defected USB cable and device malfunction from glitch (noise in clock system and data bus) should be verified especially in bad clone ESP32 board.

If the device crashed, trace decoding info is important for others to help.

This is the managed library which provides the operating status and also all error information. 

The library debug message and your own debug message for free heap are also important.

That kind of  issue you mentioned is not related to the library directly and you need to verify and debug as I mentioned above.
